apiVersion: v1
kind: Template
metadata:
  name: simple-pipeline
  annotations:
    description: "A buildconfig with a simple pipeline for testing Jenkins CICD"
    tags: "jenkins,pipeline"
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: simple-pipeline
      name: simple-pipeline
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: {}
      output: {}
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        git:
          ref: ${GITBRANCH}
          uri: ${GITURL}
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          env:
            - name: GITURL
              value: ${GITURL}
            - name: GITBRANCH
              value: ${GITBRANCH}
          jenkinsfilePath: pipelines/simple/Jenkinsfile
        type: JenkinsPipeline
      successfulBuildsHistoryLimit: 5
parameters:
- name: GITURL
  description: The URL of the repository including the simple pipeline
  value: https://github.com/eitchugo/openshift-jenkins-lab.git
  required: true
- name: GITBRANCH
  description: The branch of the repository that will be used in the pipeline
  value: master
  required: true
labels:
  app: simple-pipeline
