apiVersion: v1
kind: Template
metadata:
  name: other-namespace-pipeline
  annotations:
    description: "A buildconfig with a simple pipeline running in another namespace"
    tags: "jenkins,pipeline"
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${BC_NAME}
      name: ${BC_NAME}
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: {}
      output: {}
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        git:
          ref: ${GITBRANCH}
          uri: ${GITURL}
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          env:
            - name: GITURL
              value: ${GITURL}
            - name: GITBRANCH
              value: ${GITBRANCH}
            - name: BUILD_NAMESPACE
              value: ${BUILD_NAMESPACE}
          jenkinsfilePath: pipelines/other-namespace/Jenkinsfile
        type: JenkinsPipeline
      successfulBuildsHistoryLimit: 5
parameters:
- name: BC_NAME
  description: The name of the buildconfig that will be created
  value: other-namespace-pipeline
  required: true
- name: GITURL
  description: The URL of the repository including the simple pipeline
  value: https://github.com/eitchugo/openshift-jenkins-lab.git
  required: true
- name: GITBRANCH
  description: The branch of the repository that will be used in the pipeline
  value: master
  required: true
- name: BUILD_NAMESPACE
  description: What namespace to create build pods
  value: pipelines
  required: true
labels:
  app: other-namespace-pipeline
