apiVersion: v1
kind: Template
metadata:
  name: jenkins-services
  annotations:
    description: "Services in a project to use a central Jenkins in a specific namespace"
    tags: "jenkins,pipeline"
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: jenkins
    spec:
      type: ExternalName
      externalName: jenkins.${JENKINS_NAMESPACE}.svc.cluster.local
  - apiVersion: v1
    kind: Service
    metadata:
      name: jenkins-jnlp
    spec:
      type: ExternalName
      externalName: jenkins-jnlp.${JENKINS_NAMESPACE}.svc.cluster.local
parameters:
- name: JENKINS_NAMESPACE
  description: Namespace where Central Jenkins is located
  required: true
  value: cicd
labels:
  app: jenkins
